Started logging messages at Wed Nov 29 19:12:20 2023
Info:    Using UV tolerance 1e-06
Info:    Using UV tolerance 1e-06
Info:    HwNlibToTSLib options selected:
Info:        Points: On
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 121 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-06
Info:    Working on 0
Info:        Working on 94
Info:            Created 
Info:        Working on 95
Info:            Created 
Info:        Working on 156
Info:            Created 
Info:        Working on 273
Info:            Created 
Info:        Working on 434
Info:            Created 
Info:        Working on 630
Info:            Created 
Info:        Working on 849
Info:            Created 
Info:        Working on 602
Info:            Created 
Info:        Working on 619
Info:            Created 
Info:        Working on 840
Info:            Created 
Info:        Working on 638
Info:            Created 
Info:        Working on 444
Info:            Created 
Info:        Working on 283
Info:            Created 
Info:        Working on 168
Info:            Created 
Info:        Working on 8
Info:            Created 
Info:        Working on 143
Info:            Created 
Info:        Working on 144
Info:            Created 
Info:        Working on 240
Info:            Created 
Info:        Working on 394
Info:            Created 
Info:        Working on 593
Info:            Created 
Info:        Working on 822
Info:            Created 
Info:        Working on 1071
Info:            Created 
Info:        Working on 1328
Info:            Created 
Info:        Working on 1586
Info:            Created 
Info:        Working on 1858
Info:            Created 
Info:        Working on 1609
Info:            Created 
Info:        Working on 1350
Info:            Created 
Info:        Working on 1096
Info:            Created 
Info:        Working on 650
Info:            Created 
Info:        Working on 455
Info:            Created 
Info:        Working on 647
Info:            Created 
Info:        Working on 866
Info:            Created 
Info:        Working on 1099
Info:            Created 
Info:        Working on 1329
Info:            Created 
Info:        Working on 1078
Info:            Created 
Info:        Working on 838
Info:            Created 
Info:        Working on 612
Info:            Created 
Info:        Working on 413
Info:            Created 
Info:        Working on 250
Info:            Created 
Info:        Working on 12
Info:            Created 
Info:        Working on 224
Info:            Created 
Info:        Working on 225
Info:            Created 
Info:        Working on 361
Info:            Created 
Info:        Working on 555
Info:            Created 
Info:        Working on 781
Info:            Created 
Info:        Working on 1034
Info:            Created 
Info:        Working on 1288
Info:            Created 
Info:        Working on 1010
Info:            Created 
Info:        Working on 1027
Info:            Created 
Info:        Working on 1285
Info:            Created 
Info:        Working on 1042
Info:            Created 
Info:        Working on 791
Info:            Created 
Info:        Working on 565
Info:            Created 
Info:        Working on 373
Info:            Created 
Info:        Working on 18
Info:            Created 
Info:        Working on 348
Info:            Created 
Info:        Working on 349
Info:            Created 
Info:        Working on 523
Info:            Created 
Info:        Working on 744
Info:            Created 
Info:        Working on 1001
Info:            Created 
Info:        Working on 1268
Info:            Created 
Info:        Working on 1538
Info:            Created 
Info:        Working on 1818
Info:            Created 
Info:        Working on 2098
Info:            Created 
Info:        Working on 2387
Info:            Created 
Info:        Working on 2102
Info:            Created 
Info:        Working on 1828
Info:            Created 
Info:        Working on 1555
Info:            Created 
Info:        Working on 1054
Info:            Created 
Info:        Working on 802
Info:            Created 
Info:        Working on 1051
Info:            Created 
Info:        Working on 1307
Info:            Created 
Info:        Working on 1561
Info:            Created 
Info:        Working on 1829
Info:            Created 
Info:        Working on 1821
Info:            Created 
Info:        Working on 1546
Info:            Created 
Info:        Working on 1283
Info:            Created 
Info:        Working on 1020
Info:            Created 
Info:        Working on 763
Info:            Created 
Info:        Working on 533
Info:            Created 
Info:        Working on 28
Info:            Created 
Info:        Working on 507
Info:            Created 
Info:        Working on 508
Info:            Created 
Info:        Working on 714
Info:            Created 
Info:        Working on 967
Info:            Created 
Info:        Working on 1232
Info:            Created 
Info:        Working on 1510
Info:            Created 
Info:        Working on 1791
Info:            Created 
Info:        Working on 1489
Info:            Created 
Info:        Working on 1503
Info:            Created 
Info:        Working on 1516
Info:            Created 
Info:        Working on 1243
Info:            Created 
Info:        Working on 977
Info:            Created 
Info:        Working on 726
Info:            Created 
Info:        Working on 52
Info:            Created 
Info:        Working on 701
Info:            Created 
Info:        Working on 702
Info:            Created 
Info:        Working on 935
Info:            Created 
Info:        Working on 1197
Info:            Created 
Info:        Working on 1482
Info:            Created 
Info:        Working on 1773
Info:            Created 
Info:        Working on 2070
Info:            Created 
Info:        Working on 2372
Info:            Created 
Info:        Working on 2689
Info:            Created 
Info:        Working on 3063
Info:            Created 
Info:        Working on 3065
Info:            Created 
Info:        Working on 2696
Info:            Created 
Info:        Working on 2384
Info:            Created 
Info:        Working on 2086
Info:            Created 
Info:        Working on 1529
Info:            Created 
Info:        Working on 1254
Info:            Created 
Info:        Working on 1526
Info:            Created 
Info:        Working on 1809
Info:            Created 
Info:        Working on 2092
Info:            Created 
Info:        Working on 2385
Info:            Created 
Info:        Working on 2375
Info:            Created 
Info:        Working on 2077
Info:            Created 
Info:        Working on 1787
Info:            Created 
Info:        Working on 1499
Info:            Created 
Info:        Working on 1216
Info:            Created 
Info:        Working on 945
Info:            Created 
Info:        Working on 99
Info:            Created 
Info:        Working on 919
Info:            Created 
Info:        Working on 920
Info:            Created 
Info:        Working on 1164
Info:            Created 
Info:        Working on 1444
Info:            Created 
Info:        Working on 1732
Info:            Created 
Info:        Working on 2034
Info:            Created 
Info:        Working on 2335
Info:            Created 
Info:        Working on 2010
Info:            Created 
Info:        Working on 2027
Info:            Created 
Info:        Working on 2332
Info:            Created 
Info:        Working on 2042
Info:            Created 
Info:        Working on 1742
Info:            Created 
Info:        Working on 1454
Info:            Created 
Info:        Working on 1176
Info:            Created 
Info:        Working on 182
Info:            Created 
Info:        Working on 1151
Info:            Created 
Info:        Working on 1152
Info:            Created 
Info:        Working on 1412
Info:            Created 
Info:        Working on 1695
Info:            Created 
Info:        Working on 2001
Info:            Created 
Info:        Working on 2314
Info:            Created 
Info:        Working on 2647
Info:            Created 
Info:        Working on 3029
Info:            Created 
Info:        Working on 3447
Info:            Created 
Info:        Working on 3894
Info:            Created 
Info:        Working on 3451
Info:            Created 
Info:        Working on 3037
Info:            Created 
Info:        Working on 2663
Info:            Created 
Info:        Working on 2054
Info:            Created 
Info:        Working on 1753
Info:            Created 
Info:        Working on 2051
Info:            Created 
Info:        Working on 2352
Info:            Created 
Info:        Working on 2666
Info:            Created 
Info:        Working on 3030
Info:            Created 
Info:        Working on 2654
Info:            Created 
Info:        Working on 2330
Info:            Created 
Info:        Working on 2020
Info:            Created 
Info:        Working on 1714
Info:            Created 
Info:        Working on 1422
Info:            Created 
Info:        Working on 304
Info:            Created 
Info:        Working on 1396
Info:            Created 
Info:        Working on 1397
Info:            Created 
Info:        Working on 1671
Info:            Created 
Info:        Working on 1975
Info:            Created 
Info:        Working on 2288
Info:            Created 
Info:        Working on 2625
Info:            Created 
Info:        Working on 3011
Info:            Created 
Info:        Working on 2603
Info:            Created 
Info:        Working on 2618
Info:            Created 
Info:        Working on 3010
Info:            Created 
Info:        Working on 2629
Info:            Created 
Info:        Working on 2296
Info:            Created 
Info:        Working on 1983
Info:            Created 
Info:        Working on 1682
Info:            Created 
Info:        Working on 466
Info:            Created 
Info:        Working on 1661
Info:            Created 
Info:        Working on 1662
Info:            Created 
Info:        Working on 1945
Info:            Created 
Info:        Working on 2255
Info:            Created 
Info:        Working on 2599
Info:            Created 
Info:        Working on 2995
Info:            Created 
Info:        Working on 3432
Info:            Created 
Info:        Working on 3891
Info:            Created 
Info:        Working on 4331
Info:            Created 
Info:        Working on 4358
Info:            Created 
Info:        Working on 3944
Info:            Created 
Info:        Working on 3506
Info:            Created 
Info:        Working on 3099
Info:            Created 
Info:        Working on 2427
Info:            Created 
Info:        Working on 2305
Info:            Created 
Info:        Working on 2638
Info:            Created 
Info:        Working on 3020
Info:            Created 
Info:        Working on 3441
Info:            Created 
Info:        Working on 3892
Info:            Created 
Info:        Working on 3438
Info:            Created 
Info:        Working on 3008
Info:            Created 
Info:        Working on 2613
Info:            Created 
Info:        Working on 2271
Info:            Created 
Info:        Working on 1955
Info:            Created 
Info:        Working on 657
Info:            Created 
Info:        Working on 1856
Info:            Created 
Info:        Working on 1930
Info:            Created 
Info:        Working on 2118
Info:            Created 
Info:        Working on 2581
Info:            Created 
Info:        Working on 2980
Info:            Created 
Info:        Working on 3420
Info:            Created 
Info:        Working on 3479
Info:            Created 
Info:        Working on 2704
Info:            Created 
Info:        Working on 3068
Info:            Created 
Info:        Working on 3422
Info:            Created 
Info:        Working on 2986
Info:            Created 
Info:        Working on 2589
Info:            Created 
Info:        Working on 2244
Info:            Created 
Info:        Working on 877
Info:            Created 
Info:        Working on 2229
Info:            Created 
Info:        Working on 2230
Info:            Created 
Info:        Working on 2556
Info:            Created 
Info:        Working on 2957
Info:            Created 
Info:        Working on 3403
Info:            Created 
Info:        Working on 3874
Info:            Created 
Info:        Working on 4325
Info:            Created 
Info:        Working on 4721
Info:            Created 
Info:        Working on 4736
Info:            Created 
Info:        Working on 4355
Info:            Created 
Info:        Working on 3931
Info:            Created 
Info:        Working on 3488
Info:            Created 
Info:        Working on 3080
Info:            Created 
Info:        Working on 2415
Info:            Created 
Info:        Working on 2414
Info:            Created 
Info:        Working on 3090
Info:            Created 
Info:        Working on 3497
Info:            Created 
Info:        Working on 3937
Info:            Created 
Info:        Working on 4356
Info:            Created 
Info:        Working on 4328
Info:            Created 
Info:        Working on 3882
Info:            Created 
Info:        Working on 3414
Info:            Created 
Info:        Working on 2969
Info:            Created 
Info:        Working on 2566
Info:            Created 
Info:        Working on 1109
Info:            Created 
Info:        Working on 2543
Info:            Created 
Info:        Working on 2544
Info:            Created 
Info:        Working on 2912
Info:            Created 
Info:        Working on 3340
Info:            Created 
Info:        Working on 3806
Info:            Created 
Info:        Working on 4253
Info:            Created 
Info:        Working on 4660
Info:            Created 
Info:        Working on 5010
Info:            Created 
Info:        Working on 5308
Info:            Created 
Info:        Working on 5309
Info:            Created 
Info:        Working on 5017
Info:            Created 
Info:        Working on 4670
Info:            Created 
Info:        Working on 4277
Info:            Created 
Info:        Working on 4717
Info:            Created 
Info:        Working on 5040
Info:            Created 
Info:        Working on 4696
Info:            Created 
Info:        Working on 4289
Info:            Created 
Info:        Working on 3835
Info:            Created 
Info:        Working on 3358
Info:            Created 
Info:        Working on 2927
Info:            Created 
Info:        Working on 1360
Info:            Created 
Info:        Working on 2896
Info:            Created 
Info:        Working on 2897
Info:            Created 
Info:        Working on 3298
Info:            Created 
Info:        Working on 3749
Info:            Created 
Info:        Working on 4187
Info:            Created 
Info:        Working on 4586
Info:            Created 
Info:        Working on 4947
Info:            Created 
Info:        Working on 5259
Info:            Created 
Info:        Working on 5503
Info:            Created 
Info:        Working on 5504
Info:            Created 
Info:        Working on 5266
Info:            Created 
Info:        Working on 4957
Info:            Created 
Info:        Working on 4610
Info:            Created 
Info:        Working on 5001
Info:            Created 
Info:        Working on 5282
Info:            Created 
Info:        Working on 4980
Info:            Created 
Info:        Working on 4620
Info:            Created 
Info:        Working on 4215
Info:            Created 
Info:        Working on 3767
Info:            Created 
Info:        Working on 3313
Info:            Created 
Info:        Working on 1622
Info:            Created 
Info:        Working on 3282
Info:            Created 
Info:        Working on 3283
Info:            Created 
Info:        Working on 3710
Info:            Created 
Info:        Working on 4131
Info:            Created 
Info:        Working on 4520
Info:            Created 
Info:        Working on 4874
Info:            Created 
Info:        Working on 5198
Info:            Created 
Info:        Working on 5457
Info:            Created 
Info:        Working on 5646
Info:            Created 
Info:        Working on 5647
Info:            Created 
Info:        Working on 5464
Info:            Created 
Info:        Working on 5208
Info:            Created 
Info:        Working on 4899
Info:            Created 
Info:        Working on 5251
Info:            Created 
Info:        Working on 5478
Info:            Created 
Info:        Working on 5228
Info:            Created 
Info:        Working on 4909
Info:            Created 
Info:        Working on 4548
Info:            Created 
Info:        Working on 4149
Info:            Created 
Info:        Working on 3725
Info:            Created 
Info:        Working on 1898
Info:            Created 
Info:        Working on 3694
Info:            Created 
Info:        Working on 3695
Info:            Created 
Info:        Working on 4103
Info:            Created 
Info:        Working on 4477
Info:            Created 
Info:        Working on 4819
Info:            Created 
Info:        Working on 5134
Info:            Created 
Info:        Working on 5399
Info:            Created 
Info:        Working on 5605
Info:            Created 
Info:        Working on 5743
Info:            Created 
Info:        Working on 5744
Info:            Created 
Info:        Working on 5612
Info:            Created 
Info:        Working on 5408
Info:            Created 
Info:        Working on 5154
Info:            Created 
Info:        Working on 5450
Info:            Created 
Info:        Working on 5623
Info:            Created 
Info:        Working on 5427
Info:            Created 
Info:        Working on 5164
Info:            Created 
Info:        Working on 4844
Info:            Created 
Info:        Working on 4495
Info:            Created 
Info:        Working on 4116
Info:            Created 
Info:        Working on 2184
Info:            Created 
Info:        Working on 4087
Info:            Created 
Info:        Working on 4088
Info:            Created 
Info:        Working on 3844
Info:            Created 
Info:        Working on 4299
Info:            Created 
Info:        Working on 4705
Info:            Created 
Info:        Working on 5050
Info:            Created 
Info:        Working on 5333
Info:            Created 
Info:        Working on 5553
Info:            Created 
Info:        Working on 5708
Info:            Created 
Info:        Working on 5813
Info:            Created 
Info:        Working on 5713
Info:            Created 
Info:        Working on 5562
Info:            Created 
Info:        Working on 5343
Info:            Created 
Info:        Working on 5059
Info:            Created 
Info:        Working on 4714
Info:            Created 
Info:        Working on 4316
Info:            Created 
Info:        Working on 4278
Info:            Created 
Info:        Working on 4680
Info:            Created 
Info:        Working on 5029
Info:            Created 
Info:        Working on 5319
Info:            Created 
Info:        Working on 5542
Info:            Created 
Info:        Working on 5703
Info:            Created 
Info:        Working on 5739
Info:            Created 
Info:        Working on 5598
Info:            Created 
Info:        Working on 5389
Info:            Created 
Info:        Working on 5124
Info:            Created 
Info:        Working on 4809
Info:            Created 
Info:        Working on 4467
Info:            Created 
Info:        Working on 2493
Info:            Created 
Info:        Working on 4457
Info:            Created 
Info:        Working on 4458
Info:            Created 
Info:        Working on 4224
Info:            Created 
Info:        Working on 4630
Info:            Created 
Info:        Working on 4989
Info:            Created 
Info:        Working on 5292
Info:            Created 
Info:        Working on 5523
Info:            Created 
Info:        Working on 5691
Info:            Created 
Info:        Working on 5807
Info:            Created 
Info:        Working on 5877
Info:            Created 
Info:        Working on 5812
Info:            Created 
Info:        Working on 5700
Info:            Created 
Info:        Working on 5533
Info:            Created 
Info:        Working on 5301
Info:            Created 
Info:        Working on 4998
Info:            Created 
Info:        Working on 4647
Info:            Created 
Info:        Working on 4611
Info:            Created 
Info:        Working on 4967
Info:            Created 
Info:        Working on 5278
Info:            Created 
Info:        Working on 5514
Info:            Created 
Info:        Working on 5683
Info:            Created 
Info:        Working on 5802
Info:            Created 
Info:        Working on 5832
Info:            Created 
Info:        Working on 5737
Info:            Created 
Info:        Working on 5592
Info:            Created 
Info:        Working on 5380
Info:            Created 
Info:        Working on 5114
Info:            Created 
Info:        Working on 4799
Info:            Created 
Info:        Working on 2846
Info:            Created 
Info:        Working on 4789
Info:            Created 
Info:        Working on 4790
Info:            Created 
Info:        Working on 4557
Info:            Created 
Info:        Working on 4918
Info:            Created 
Info:        Working on 5238
Info:            Created 
Info:        Working on 5488
Info:            Created 
Info:        Working on 5665
Info:            Created 
Info:        Working on 5790
Info:            Created 
Info:        Working on 5871
Info:            Created 
Info:        Working on 5906
Info:            Created 
Info:        Working on 5876
Info:            Created 
Info:        Working on 5799
Info:            Created 
Info:        Working on 5674
Info:            Created 
Info:        Working on 5497
Info:            Created 
Info:        Working on 5248
Info:            Created 
Info:        Working on 4934
Info:            Created 
Info:        Working on 4900
Info:            Created 
Info:        Working on 5218
Info:            Created 
Info:        Working on 5475
Info:            Created 
Info:        Working on 5656
Info:            Created 
Info:        Working on 5782
Info:            Created 
Info:        Working on 5866
Info:            Created 
Info:        Working on 5905
Info:            Created 
Info:        Working on 5888
Info:            Created 
Info:        Working on 5830
Info:            Created 
Info:        Working on 5731
Info:            Created 
Info:        Working on 5583
Info:            Created 
Info:        Working on 5369
Info:            Created 
Info:        Working on 5103
Info:            Created 
Info:        Working on 3235
Info:            Created 
Info:        Working on 5093
Info:            Created 
Info:        Working on 5094
Info:            Created 
Info:        Working on 4853
Info:            Created 
Info:        Working on 5173
Info:            Created 
Info:        Working on 5437
Info:            Created 
Info:        Working on 5633
Info:            Created 
Info:        Working on 5762
Info:            Created 
Info:        Working on 5851
Info:            Created 
Info:        Working on 5899
Info:            Created 
Info:        Working on 5912
Info:            Created 
Info:        Working on 5904
Info:            Created 
Info:        Working on 5860
Info:            Created 
Info:        Working on 5771
Info:            Created 
Info:        Working on 5642
Info:            Created 
Info:        Working on 5447
Info:            Created 
Info:        Working on 5187
Info:            Created 
Info:        Working on 5155
Info:            Created 
Info:        Working on 5418
Info:            Created 
Info:        Working on 5621
Info:            Created 
Info:        Working on 5753
Info:            Created 
Info:        Working on 5843
Info:            Created 
Info:        Working on 5894
Info:            Created 
Info:        Working on 5911
Info:            Created 
Info:        Working on 5910
Info:            Created 
Info:        Working on 5885
Info:            Created 
Info:        Working on 5823
Info:            Created 
Info:        Working on 5722
Info:            Created 
Info:        Working on 5573
Info:            Created 
Info:        Working on 5359
Info:            Created 
Info:        Working on 3654
Info:            Created 
Info:        Working on 5188
Info:            Created 
Info:        Working on 5324
Info:            Created 
Info:        Working on 4059
Info:            Created 
Info:        Working on 4429
Info:            Created 
Info:        Working on 4760
Info:            Created 
Info:        Working on 4017
Info:            Created 
Info:        Working on 4763
Info:            Created 
Info:        Working on 4510
Info:            Created 
Info:        Working on 4487
Info:            Created 
Info:        Working on 4935
Info:            Created 
Info:        Working on 5349
Info:            Created 
Info:        Working on 4835
Info:            Created 
Info:        Working on 4165
Info:            Created 
Info:        Working on 4574
Info:            Created 
Info:        Working on 4170
Info:            Created 
Info:        Working on 4572
Info:            Created 
Info:        Working on 4174
Info:            Created 
Info:        Working on 4141
Info:            Created 
Info:        Working on 4648
Info:            Created 
Info:        Working on 5280
Info:            Created 
Info:        Working on 4539
Info:            Created 
Info:        Working on 3783
Info:            Created 
Info:        Working on 4241
Info:            Created 
Info:        Working on 3789
Info:            Created 
Info:        Working on 4239
Info:            Created 
Info:        Working on 3793
Info:            Created 
Info:        Working on 3759
Info:            Created 
Info:        Working on 4317
Info:            Created 
Info:        Working on 5031
Info:            Created 
Info:        Working on 4206
Info:            Created 
Info:        Working on 3374
Info:            Created 
Info:        Working on 3862
Info:            Created 
Info:        Working on 3381
Info:            Created 
Info:        Working on 3859
Info:            Created 
Info:        Working on 3385
Info:            Created 
Info:        Working on 3350
Info:            Created 
Info:        Working on 5545
Info:            Created 
Info:        Working on 3826
Info:            Created 
Info:        Working on 3165
Info:            Created 
Info:        Working on 3166
Info:            Created 
Info:        Working on 3590
Info:            Created 
Info:        Working on 5563
Info:            Created 
Info:        Working on 4020
Info:            Created 
Info:        Working on 3581
Info:            Created 
Info:        Working on 3582
Info:            Created 
Info:        Working on 3739
Info:            Created 
Info:        Working on 5675
Info:            Created 
Info:        Working on 4177
Info:            Created 
Info:        Working on 4008
Info:            Created 
Info:        Working on 4009
Info:            Created 
Info:        Working on 3330
Info:            Created 
Info:        Working on 5534
Info:            Created 
Info:        Working on 3796
Info:            Created 
Info:        Working on 3864
Info:            Created 
Info:        Working on 3860
Info:            Created 
Info:        Working on 2946
Info:            Created 
Info:        Working on 3174
Info:            Created 
Info:        Working on 3146
Info:            Created 
Info:        Working on 3478
Info:            Created 
Info:        Working on 3393
Info:            Created 
Info:        Working on 2489
Info:            Created 
Info:        Working on 2789
Info:            Created 
Info:        Working on 3060
Info:            Created 
Info:        Working on 3648
Info:            Created 
Info:        Working on 4006
Info:            Created 
Info:        Working on 3148
Info:            Created 
Info:        Working on 3180
Info:            Created 
Info:        Working on 4055
Info:            Created 
Info:        Working on 2488
Info:            Created 
Info:        Working on 3231
Info:            Created 
Info:        Working on 2790
Info:            Created 
Info:        Working on 3650
Info:            Created 
Info:        Working on 2839
Info:            Created 
Info:        Working on 3230
Info:            Created 
Info:        Working on 2828
Info:            Created 
Info:        Working on 3059
Info:            Created 
Info:        Working on 3224
Info:            Created 
Info:        Working on 3218
Info:            Created 
Info:        Working on 3524
Info:            Created 
Info:        Working on 3645
Info:            Created 
Info:        Working on 3641
Info:            Created 
Info:        Working on 3961
Info:            Created 
Info:        Working on 4053
Info:            Created 
Info:        Working on 4049
Info:            Created 
Info:        Working on 4367
Info:            Created 
Info:        Working on 4427
Info:            Created 
Info:        Working on 4041
Info:            Created 
Info:        Working on 4734
Info:            Created 
Info:        Working on 4767
Info:            Created 
Info:        Working on 3621
Info:            Created 
Info:        Working on 3471
Info:            Created 
Info:        Working on 4421
Info:            Created 
Info:        Working on 3199
Info:            Created 
Info:        Working on 3470
Info:            Created 
Info:        Working on 3917
Info:            Created 
Info:        Working on 2813
Info:            Created 
Info:        Working on 3631
Info:            Created 
Info:        Working on 3626
Info:            Created 
Info:        Working on 3206
Info:            Created 
Info:        Working on 3569
Info:            Created 
Info:        Working on 3477
Info:            Created 
Info:        Working on 3547
Info:            Created 
Info:        Working on 3989
Info:            Created 
Info:        Working on 3962
Info:            Created 
Info:        Working on 3985
Info:            Created 
Info:        Working on 4395
Info:            Created 
Info:        Working on 4371
Info:            Created 
Info:        Working on 4391
Info:            Created 
Info:        Working on 4756
Info:            Created 
Info:        Working on 4741
Info:            Created 
Info:        Working on 4754
Info:            Created 
Info:        Working on 5072
Info:            Created 
Info:        Working on 4733
Info:            Created 
Info:        Working on 4757
Info:            Created 
Info:        Working on 5345
Info:            Created 
Info:        Working on 3913
Info:            Created 
Info:        Working on 4399
Info:            Created 
Info:        Working on 5064
Info:            Created 
Info:        Working on 3906
Info:            Created 
Info:        Working on 3997
Info:            Created 
Info:        Working on 4726
Info:            Created 
Info:        Working on 4404
Info:            Created 
Info:        Working on 3562
Info:            Created 
Info:        Working on 4401
Info:            Created 
Info:        Working on 4004
Info:            Created 
Info:        Working on 3597
Info:            Created 
Info:        Working on 4022
Info:            Created 
Info:        Working on 2797
Info:            Created 
Info:        Working on 2798
Info:            Created 
Info:        Working on 1604
Info:            Created 
Info:        Working on 1605
Info:            Created 
Info:        Working on 2139
Info:            Created 
Info:        Working on 2140
Info:            Created 
Info:        Working on 1104
Info:            Created 
Info:        Working on 1105
Info:            Created 
Info:        Working on 1579
Info:            Created 
Info:        Working on 1580
Info:            Created 
Info:        Working on 2110
Info:            Created 
Info:        Working on 2111
Info:            Created 
Info:        Working on 2681
Info:            Created 
Info:        Working on 2682
Info:            Created 
Info:        Working on 1356
Info:            Created 
Info:        Working on 1615
Info:            Created 
Info:        Working on 3532
Info:            Created 
Info:        Working on 3533
Info:            Created 
Info:        Working on 1885
Info:            Created 
Info:        Working on 2154
Info:            Created 
Info:        Working on 2431
Info:            Created 
Info:        Working on 2739
Info:            Created 
Info:        Working on 3103
Info:            Created 
Info:        Working on 3509
Info:            Created 
Info:        Working on 3946
Info:            Created 
Info:        Working on 4746
Info:            Created 
Info:        Working on 4376
Info:            Created 
Info:        Working on 4745
Info:            Created 
Info:        Working on 3972
Info:            Created 
Info:        Working on 4032
Info:            Created 
Info:        Working on 3613
Info:            Created 
Info:        Working on 4414
Info:            Created 
Info:        Working on 4380
Info:            Created 
Info:        Working on 3188
Info:            Created 
Info:        Working on 1855
Info:            Created 
Info:        Working on 2132
Info:            Created 
Info:        Working on 2406
Info:            Created 
Info:        Working on 2974
Info:            Created 
Info:        Working on 2397
Info:            Created 
Info:        Working on 2716
Info:            Created 
Info:        Working on 2574
Info:            Created 
Info:        Working on 1877
Info:            Created 
Info:        Working on 2149
Info:            Created 
Info:        Working on 2290
Info:            Created 
Info:        Working on 2279
Info:            Created 
Info:        Working on 2420
Info:            Created 
Info:        Working on 2261
Info:            Created 
Info:        Working on 1964
Info:            Created 
Info:        Working on 1467
Info:            Created 
Info:        Working on 1758
Info:            Created 
Info:        Working on 1736
Info:            Created 
Info:        Working on 1723
Info:            Created 
Info:        Working on 2319
Info:            Created 
Info:        Working on 1704
Info:            Created 
Info:        Working on 1431
Info:            Created 
Info:        Working on 990
Info:            Created 
Info:        Working on 1259
Info:            Created 
Info:        Working on 1236
Info:            Created 
Info:        Working on 1223
Info:            Created 
Info:        Working on 1777
Info:            Created 
Info:        Working on 1206
Info:            Created 
Info:        Working on 954
Info:            Created 
Info:        Working on 578
Info:            Created 
Info:        Working on 807
Info:            Created 
Info:        Working on 785
Info:            Created 
Info:        Working on 772
Info:            Created 
Info:        Working on 1273
Info:            Created 
Info:        Working on 753
Info:            Created 
Info:        Working on 542
Info:            Created 
Info:        Working on 296
Info:            Created 
Info:        Working on 460
Info:            Created 
Info:        Working on 438
Info:            Created 
Info:        Working on 422
Info:            Created 
Info:        Working on 827
Info:            Created 
Info:        Working on 403
Info:            Created 
Info:        Working on 260
Info:            Created 
Info:        Working on 991
Info:            Created 
Info:        Working on 425
Info:            Created 
Info:        Working on 623
Info:            Created 
Info:        Working on 1991
Info:            Created 
Info:        Working on 846
Info:            Created 
Info:        Working on 1081
Info:            Created 
Info:        Working on 297
Info:            Created 
Info:        Working on 178
Info:            Created 
Info:        Working on 300
Info:            Created 
Info:        Working on 579
Info:            Created 
Info:        Working on 383
Info:            Created 
Info:        Working on 583
Info:            Created 
Info:        Working on 2407
Info:            Created 
Info:        Working on 811
Info:            Created 
Info:        Working on 1057
Info:            Created 
Info:        Working on 1468
Info:            Created 
Info:        Working on 1186
Info:            Created 
Info:        Working on 1472
Info:            Created 
Info:        Working on 1762
Info:            Created 
Info:        Working on 2057
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 4.24996e-05
Info:        Using 3D tolerance 1e-06
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Wed Nov 29 19:12:27 2023
