Started logging messages at Fri Oct 20 09:29:28 2023
Info:    Using UV tolerance 1e-06
Info:    Using UV tolerance 1e-06
Info:    HwNlibToTSLib options selected:
Info:        Points: On
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 25 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-06
Info:    Working on 0
Info:        Working on 76
Info:            Created 
Info:        Working on 77
Info:            Created 
Info:        Working on 115
Info:            Created 
Info:        Working on 8
Info:            Created 
Info:        Working on 110
Info:            Created 
Info:        Working on 111
Info:            Created 
Info:        Working on 164
Info:            Created 
Info:        Working on 12
Info:            Created 
Info:        Working on 159
Info:            Created 
Info:        Working on 160
Info:            Created 
Info:        Working on 222
Info:            Created 
Info:        Working on 217
Info:            Created 
Info:        Working on 218
Info:            Created 
Info:        Working on 18
Info:            Created 
Info:        Working on 204
Info:            Created 
Info:        Working on 205
Info:            Created 
Info:        Working on 272
Info:            Created 
Info:        Working on 268
Info:            Created 
Info:        Working on 28
Info:            Created 
Info:        Working on 264
Info:            Created 
Info:        Working on 265
Info:            Created 
Info:        Working on 343
Info:            Created 
Info:        Working on 339
Info:            Created 
Info:        Working on 49
Info:            Created 
Info:        Working on 335
Info:            Created 
Info:        Working on 336
Info:            Created 
Info:        Working on 428
Info:            Created 
Info:        Working on 350
Info:            Created 
Info:        Working on 424
Info:            Created 
Info:        Working on 81
Info:            Created 
Info:        Working on 420
Info:            Created 
Info:        Working on 421
Info:            Created 
Info:        Working on 519
Info:            Created 
Info:        Working on 613
Info:            Created 
Info:        Working on 122
Info:            Created 
Info:        Working on 513
Info:            Created 
Info:        Working on 514
Info:            Created 
Info:        Working on 608
Info:            Created 
Info:        Working on 693
Info:            Created 
Info:        Working on 173
Info:            Created 
Info:        Working on 602
Info:            Created 
Info:        Working on 603
Info:            Created 
Info:        Working on 691
Info:            Created 
Info:        Working on 735
Info:            Created 
Info:        Working on 235
Info:            Created 
Info:        Working on 439
Info:            Created 
Info:        Working on 440
Info:            Created 
Info:        Working on 355
Info:            Created 
Info:        Working on 436
Info:            Created 
Info:        Working on 287
Info:            Created 
Info:        Working on 706
Info:            Created 
Info:        Working on 707
Info:            Created 
Info:        Working on 701
Info:            Created 
Info:        Working on 700
Info:            Created 
Info:        Working on 366
Info:            Created 
Info:        Working on 713
Info:            Created 
Info:        Working on 444
Info:            Created 
Info:        Working on 574
Info:            Created 
Info:        Working on 723
Info:            Created 
Info:        Working on 657
Info:            Created 
Info:        Working on 742
Info:            Created 
Info:        Working on 754
Info:            Created 
Info:        Working on 755
Info:            Created 
Info:        Working on 532
Info:            Created 
Info:        Working on 730
Info:            Created 
Info:        Working on 591
Info:            Created 
Info:        Working on 590
Info:            Created 
Info:        Working on 732
Info:            Created 
Info:        Working on 625
Info:            Created 
Info:        Working on 741
Info:            Created 
Info:        Working on 522
Info:            Created 
Info:        Working on 724
Info:            Created 
Info:        Working on 611
Info:            Created 
Info:        Working on 573
Info:            Created 
Info:        Working on 668
Info:            Created 
Info:        Working on 712
Info:            Created 
Info:        Working on 726
Info:            Created 
Info:        Working on 649
Info:            Created 
Info:        Working on 675
Info:            Created 
Info:        Working on 645
Info:            Created 
Info:        Working on 646
Info:            Created 
Info:        Working on 228
Info:            Created 
Info:        Working on 293
Info:            Created 
Info:        Working on 476
Info:            Created 
Info:        Working on 396
Info:            Created 
Info:        Working on 370
Info:            Created 
Info:        Working on 481
Info:            Created 
Info:        Working on 450
Info:            Created 
Info:        Working on 397
Info:            Created 
Info:        Working on 541
Info:            Created 
Info:        Working on 494
Info:            Created 
Info:        Working on 118
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 3.21063e-05
Info:        Using 3D tolerance 1e-06
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Fri Oct 20 09:29:29 2023
