Started logging messages at Sat Nov  4 18:33:58 2023
Info:    Using UV tolerance 1e-06
Info:    Using UV tolerance 1e-06
Info:    HwNlibToTSLib options selected:
Info:        Points: On
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 22 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-06
Info:    Working on 0
Info:        Working on 87
Info:            Created 
Info:        Working on 88
Info:            Created 
Info:        Working on 133
Info:            Created 
Info:        Working on 140
Info:            Created 
Info:        Working on 8
Info:            Created 
Info:        Working on 121
Info:            Created 
Info:        Working on 122
Info:            Created 
Info:        Working on 186
Info:            Created 
Info:        Working on 12
Info:            Created 
Info:        Working on 180
Info:            Created 
Info:        Working on 181
Info:            Created 
Info:        Working on 18
Info:            Created 
Info:        Working on 250
Info:            Created 
Info:        Working on 251
Info:            Created 
Info:        Working on 319
Info:            Created 
Info:        Working on 28
Info:            Created 
Info:        Working on 316
Info:            Created 
Info:        Working on 317
Info:            Created 
Info:        Working on 50
Info:            Created 
Info:        Working on 331
Info:            Created 
Info:        Working on 334
Info:            Created 
Info:        Working on 371
Info:            Created 
Info:        Working on 92
Info:            Created 
Info:        Working on 433
Info:            Created 
Info:        Working on 453
Info:            Created 
Info:        Working on 386
Info:            Created 
Info:        Working on 154
Info:            Created 
Info:        Working on 353
Info:            Created 
Info:        Working on 354
Info:            Created 
Info:        Working on 401
Info:            Created 
Info:        Working on 443
Info:            Created 
Info:        Working on 470
Info:            Created 
Info:        Working on 468
Info:            Created 
Info:        Working on 274
Info:            Created 
Info:        Working on 222
Info:            Created 
Info:        Working on 204
Info:            Created 
Info:        Working on 269
Info:            Created 
Info:        Working on 266
Info:            Created 
Info:        Working on 370
Info:            Created 
Info:        Working on 336
Info:            Created 
Info:        Working on 359
Info:            Created 
Info:        Working on 328
Info:            Created 
Info:        Working on 475
Info:            Created 
Info:        Working on 390
Info:            Created 
Info:        Working on 479
Info:            Created 
Info:        Working on 436
Info:            Created 
Info:        Working on 420
Info:            Created 
Info:        Working on 407
Info:            Created 
Info:        Working on 458
Info:            Created 
Info:        Working on 447
Info:            Created 
Info:        Working on 221
Info:            Created 
Info:        Working on 290
Info:            Created 
Info:        Working on 478
Info:            Created 
Info:        Working on 218
Info:            Created 
Info:        Working on 305
Info:            Created 
Info:        Working on 374
Info:            Created 
Info:        Working on 192
Info:            Created 
Info:        Working on 151
Info:            Created 
Info:        Working on 225
Info:            Created 
Info:        Working on 307
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 9.49511e-05
Info:        Using 3D tolerance 1e-06
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Sat Nov  4 18:33:58 2023
